import { Zone } from '@/types/curriculum'

export const ZONES: Zone[] = [
  {
    id: 'init-valley',
    name: 'Init Valley',
    description: 'Where every repository is born',
    icon: '🏔️',
    position: { x: 250, y: 110 },
    requiredZone: null,
    lessonIds: ['what-is-git', 'git-init', 'git-clone'],
  },
  {
    id: 'staging-plains',
    name: 'Staging Plains',
    description: 'Master the art of staging changes',
    icon: '🌿',
    position: { x: 250, y: 310 },
    requiredZone: 'init-valley',
    lessonIds: ['git-status', 'git-add', 'gitignore'],
  },
  {
    id: 'commit-forge',
    name: 'Commit Forge',
    description: 'Forge your history, one commit at a time',
    icon: '🔥',
    position: { x: 250, y: 510 },
    requiredZone: 'staging-plains',
    lessonIds: ['git-commit', 'git-log', 'git-diff', 'amending-commits'],
  },
  {
    id: 'branch-forest',
    name: 'Branch Forest',
    description: 'Navigate the parallel paths of branching',
    icon: '🌳',
    position: { x: 250, y: 710 },
    requiredZone: 'commit-forge',
    lessonIds: ['what-are-branches', 'git-branch', 'git-checkout', 'detached-head'],
  },
  {
    id: 'merge-battlegrounds',
    name: 'Merge Battlegrounds',
    description: 'Where branches collide and conflicts are resolved',
    icon: '⚔️',
    position: { x: 250, y: 910 },
    requiredZone: 'branch-forest',
    lessonIds: ['git-merge', 'merge-conflicts', 'git-stash'],
  },
  {
    id: 'rebase-temple',
    name: 'Rebase Temple',
    description: 'Rewrite history with precision and wisdom',
    icon: '🌀',
    position: { x: 250, y: 1110 },
    requiredZone: 'merge-battlegrounds',
    lessonIds: ['git-rebase', 'interactive-rebase', 'git-cherry-pick'],
  },
]
